# Generated by Django 5.0.3 on 2024-05-10 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='category',
        ),
    ]
