# Generated by Django 5.0.3 on 2024-05-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_remove_property_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
