# Generated by Django 5.0.3 on 2024-05-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0004_user_city_user_phone_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('query_text', models.TextField(blank=True, null=True, unique=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
